//
// Created by volodymyr on 02.05.19.
//

#ifndef INCUBATORTESTCLIENT_REGISTERDEVICEREQUESTMESSAGEENCODER_H
#define INCUBATORTESTCLIENT_REGISTERDEVICEREQUESTMESSAGEENCODER_H

#include "../../proto/RegisterDeviceRequestMessage.pb.h"

extern const RegisterDeviceRequestMessage REGISTER_DEVICE_REQUEST_MESSAGE_init_encoder;

#endif //INCUBATORTESTCLIENT_REGISTERDEVICEREQUESTMESSAGEENCODER_H
