//
// Created by volodymyr on 02.05.19.
//

#ifndef INCUBATORTESTCLIENT_STARTNEWSESSIONWITHCALENDARMESSAGEPARSER_H
#define INCUBATORTESTCLIENT_STARTNEWSESSIONWITHCALENDARMESSAGEPARSER_H

#include "../../proto/StartNewSessionWithCalendarMessage.pb.h"

extern const StartNewSessionWithCalendarMessage START_NEW_SESSION_WITH_CALENDAR_MESSAGE_init_parser;
#endif //INCUBATORTESTCLIENT_STARTNEWSESSIONWITHCALENDARMESSAGEPARSER_H
