/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu May  2 00:38:34 2019. */

#ifndef PB_CHANGECURRENTSESSIONDAYPARAMETERSMESSAGE_PB_H_INCLUDED
#define PB_CHANGECURRENTSESSIONDAYPARAMETERSMESSAGE_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ChangeCurrentSessionDayParametersMessage {
    uint32_t dayNumber;
    float temperature;
    float humidity;
    uint32_t rotationCount;
    uint32_t ventilationCount;
    uint32_t ventilationDuration;
/* @@protoc_insertion_point(struct:ChangeCurrentSessionDayParametersMessage) */
} ChangeCurrentSessionDayParametersMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ChangeCurrentSessionDayParametersMessage_init_default {0, 0, 0, 0, 0, 0}
#define ChangeCurrentSessionDayParametersMessage_init_zero {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ChangeCurrentSessionDayParametersMessage_dayNumber_tag 2
#define ChangeCurrentSessionDayParametersMessage_temperature_tag 3
#define ChangeCurrentSessionDayParametersMessage_humidity_tag 4
#define ChangeCurrentSessionDayParametersMessage_rotationCount_tag 5
#define ChangeCurrentSessionDayParametersMessage_ventilationCount_tag 6
#define ChangeCurrentSessionDayParametersMessage_ventilationDuration_tag 7

/* Struct field encoding specification for nanopb */
extern const pb_field_t ChangeCurrentSessionDayParametersMessage_fields[7];

/* Maximum encoded size of messages (where known) */
#define ChangeCurrentSessionDayParametersMessage_size 34

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CHANGECURRENTSESSIONDAYPARAMETERSMESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
