/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Thu May  2 00:38:34 2019. */

#include "ChangeCurrentSessionDayParametersMessage.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ChangeCurrentSessionDayParametersMessage_fields[7] = {
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , FIRST, ChangeCurrentSessionDayParametersMessage, dayNumber, dayNumber, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, ChangeCurrentSessionDayParametersMessage, temperature, dayNumber, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, ChangeCurrentSessionDayParametersMessage, humidity, temperature, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, ChangeCurrentSessionDayParametersMessage, rotationCount, humidity, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, ChangeCurrentSessionDayParametersMessage, ventilationCount, rotationCount, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, ChangeCurrentSessionDayParametersMessage, ventilationDuration, ventilationCount, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
