/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu May  2 00:38:34 2019. */

#ifndef PB_FORCEROTATEEGGSMESSAGE_PB_H_INCLUDED
#define PB_FORCEROTATEEGGSMESSAGE_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ForceRotateEggsMessage {
    uint32_t rotateCount;
/* @@protoc_insertion_point(struct:ForceRotateEggsMessage) */
} ForceRotateEggsMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ForceRotateEggsMessage_init_default      {0}
#define ForceRotateEggsMessage_init_zero         {0}

/* Field tags (for use in manual encoding/decoding) */
#define ForceRotateEggsMessage_rotateCount_tag   2

/* Struct field encoding specification for nanopb */
extern const pb_field_t ForceRotateEggsMessage_fields[2];

/* Maximum encoded size of messages (where known) */
#define ForceRotateEggsMessage_size              6

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define FORCEROTATEEGGSMESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
