/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu May  2 00:38:34 2019. */

#ifndef PB_FORCEVENTILATEINCUBATORMESSAGE_PB_H_INCLUDED
#define PB_FORCEVENTILATEINCUBATORMESSAGE_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ForceVentilateIncubatorMessage {
    uint32_t duration;
/* @@protoc_insertion_point(struct:ForceVentilateIncubatorMessage) */
} ForceVentilateIncubatorMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ForceVentilateIncubatorMessage_init_default {0}
#define ForceVentilateIncubatorMessage_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define ForceVentilateIncubatorMessage_duration_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t ForceVentilateIncubatorMessage_fields[2];

/* Maximum encoded size of messages (where known) */
#define ForceVentilateIncubatorMessage_size      6

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define FORCEVENTILATEINCUBATORMESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
