/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Thu May  2 00:38:34 2019. */

#include "ForceRotateEggsMessage.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ForceRotateEggsMessage_fields[2] = {
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , FIRST, ForceRotateEggsMessage, rotateCount, rotateCount, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
