/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu May  2 00:38:34 2019. */

#ifndef PB_INCOMEMESSAGE_PB_H_INCLUDED
#define PB_INCOMEMESSAGE_PB_H_INCLUDED
#include "pb.h"

#include "IncubatorIncomeMessagePayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _IncomeMessage {
    uint32_t deviceId;
    bool has_replyWith;
    int32_t replyWith;
    bool has_inReplyTo;
    uint32_t inReplyTo;
    bool has_incubatorMessagePayload;
    IncubatorIncomeMessagePayload incubatorMessagePayload;
/* @@protoc_insertion_point(struct:IncomeMessage) */
} IncomeMessage;

/* Default values for struct fields */
extern const int32_t IncomeMessage_replyWith_default;

/* Initializer values for message structs */
#define IncomeMessage_init_default               {0, false, -1, false, 0, false, IncubatorIncomeMessagePayload_init_default}
#define IncomeMessage_init_zero                  {0, false, 0, false, 0, false, IncubatorIncomeMessagePayload_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define IncomeMessage_deviceId_tag               1
#define IncomeMessage_replyWith_tag              2
#define IncomeMessage_inReplyTo_tag              3
#define IncomeMessage_incubatorMessagePayload_tag 4

/* Struct field encoding specification for nanopb */
extern const pb_field_t IncomeMessage_fields[5];

/* Maximum encoded size of messages (where known) */
#define IncomeMessage_size                       (95 + ChangeCurrentSessionDayHumidityMessage_size + ChangeCurrentSessionDayParametersMessage_size + ChangeCurrentSessionDayRotationCountMessage_size + ChangeCurrentSessionDayTemperatureMessage_size + ChangeCurrentSessionDayVentillationCountMessage_size + ChangeCurrentSessionDayVentillationDurationMessage_size + ForceRotateEggsMessage_size + ForceVentilateIncubatorMessage_size + StartNewSessionWithBirdTypeMessage_size + StartNewSessionWithCalendarMessage_size + RegistrationSuccessNotificationMessage_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define INCOMEMESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
