/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Thu May  2 00:38:34 2019. */

#include "IncubatorIncomeMessagePayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t IncubatorIncomeMessagePayload_fields[12] = {
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , FIRST, IncubatorIncomeMessagePayload, changeDayHumidityMessage, changeDayHumidityMessage, &ChangeCurrentSessionDayHumidityMessage_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, IncubatorIncomeMessagePayload, changeDayParametersMessage, changeDayHumidityMessage, &ChangeCurrentSessionDayParametersMessage_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, IncubatorIncomeMessagePayload, changeDayRotationCountMessage, changeDayParametersMessage, &ChangeCurrentSessionDayRotationCountMessage_fields),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, IncubatorIncomeMessagePayload, changeDayTemperatureMessage, changeDayRotationCountMessage, &ChangeCurrentSessionDayTemperatureMessage_fields),
    PB_FIELD(  7, MESSAGE , OPTIONAL, STATIC  , OTHER, IncubatorIncomeMessagePayload, changeDayVentillationCountMessage, changeDayTemperatureMessage, &ChangeCurrentSessionDayVentillationCountMessage_fields),
    PB_FIELD(  8, MESSAGE , OPTIONAL, STATIC  , OTHER, IncubatorIncomeMessagePayload, changeDayVentillationDurationMessage, changeDayVentillationCountMessage, &ChangeCurrentSessionDayVentillationDurationMessage_fields),
    PB_FIELD(  9, MESSAGE , OPTIONAL, STATIC  , OTHER, IncubatorIncomeMessagePayload, forceRotateEggsMessage, changeDayVentillationDurationMessage, &ForceRotateEggsMessage_fields),
    PB_FIELD( 10, MESSAGE , OPTIONAL, STATIC  , OTHER, IncubatorIncomeMessagePayload, forceVentilateIncubatorMessage, forceRotateEggsMessage, &ForceVentilateIncubatorMessage_fields),
    PB_FIELD( 11, MESSAGE , OPTIONAL, STATIC  , OTHER, IncubatorIncomeMessagePayload, startNewSessionWithBirdTypeMessage, forceVentilateIncubatorMessage, &StartNewSessionWithBirdTypeMessage_fields),
    PB_FIELD( 12, MESSAGE , OPTIONAL, STATIC  , OTHER, IncubatorIncomeMessagePayload, startNewSessionWithCalendarMessage, startNewSessionWithBirdTypeMessage, &StartNewSessionWithCalendarMessage_fields),
    PB_FIELD( 13, MESSAGE , OPTIONAL, STATIC  , OTHER, IncubatorIncomeMessagePayload, successRegistrationMessage, startNewSessionWithCalendarMessage, &RegistrationSuccessNotificationMessage_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(IncubatorIncomeMessagePayload, changeDayHumidityMessage) < 65536 && pb_membersize(IncubatorIncomeMessagePayload, changeDayParametersMessage) < 65536 && pb_membersize(IncubatorIncomeMessagePayload, changeDayRotationCountMessage) < 65536 && pb_membersize(IncubatorIncomeMessagePayload, changeDayTemperatureMessage) < 65536 && pb_membersize(IncubatorIncomeMessagePayload, changeDayVentillationCountMessage) < 65536 && pb_membersize(IncubatorIncomeMessagePayload, changeDayVentillationDurationMessage) < 65536 && pb_membersize(IncubatorIncomeMessagePayload, forceRotateEggsMessage) < 65536 && pb_membersize(IncubatorIncomeMessagePayload, forceVentilateIncubatorMessage) < 65536 && pb_membersize(IncubatorIncomeMessagePayload, startNewSessionWithBirdTypeMessage) < 65536 && pb_membersize(IncubatorIncomeMessagePayload, startNewSessionWithCalendarMessage) < 65536 && pb_membersize(IncubatorIncomeMessagePayload, successRegistrationMessage) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_IncubatorIncomeMessagePayload)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(IncubatorIncomeMessagePayload, changeDayHumidityMessage) < 256 && pb_membersize(IncubatorIncomeMessagePayload, changeDayParametersMessage) < 256 && pb_membersize(IncubatorIncomeMessagePayload, changeDayRotationCountMessage) < 256 && pb_membersize(IncubatorIncomeMessagePayload, changeDayTemperatureMessage) < 256 && pb_membersize(IncubatorIncomeMessagePayload, changeDayVentillationCountMessage) < 256 && pb_membersize(IncubatorIncomeMessagePayload, changeDayVentillationDurationMessage) < 256 && pb_membersize(IncubatorIncomeMessagePayload, forceRotateEggsMessage) < 256 && pb_membersize(IncubatorIncomeMessagePayload, forceVentilateIncubatorMessage) < 256 && pb_membersize(IncubatorIncomeMessagePayload, startNewSessionWithBirdTypeMessage) < 256 && pb_membersize(IncubatorIncomeMessagePayload, startNewSessionWithCalendarMessage) < 256 && pb_membersize(IncubatorIncomeMessagePayload, successRegistrationMessage) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_IncubatorIncomeMessagePayload)
#endif


/* @@protoc_insertion_point(eof) */
