/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Thu May  2 00:38:34 2019. */

#include "IncubationSessionInformationMessage.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t IncubationSessionInformationMessage_fields[6] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, IncubationSessionInformationMessage, temperature, temperature, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, IncubationSessionInformationMessage, humidity, temperature, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, IncubationSessionInformationMessage, ventilationCount, humidity, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, IncubationSessionInformationMessage, ventilationDuration, ventilationCount, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, IncubationSessionInformationMessage, rotationCount, ventilationDuration, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
