/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu May  2 00:38:34 2019. */

#ifndef PB_INCUBATIONSESSIONINFORMATIONMESSAGE_PB_H_INCLUDED
#define PB_INCUBATIONSESSIONINFORMATIONMESSAGE_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _IncubationSessionInformationMessage {
    float temperature;
    float humidity;
    uint32_t ventilationCount;
    uint32_t ventilationDuration;
    uint32_t rotationCount;
/* @@protoc_insertion_point(struct:IncubationSessionInformationMessage) */
} IncubationSessionInformationMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define IncubationSessionInformationMessage_init_default {0, 0, 0, 0, 0}
#define IncubationSessionInformationMessage_init_zero {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define IncubationSessionInformationMessage_temperature_tag 1
#define IncubationSessionInformationMessage_humidity_tag 2
#define IncubationSessionInformationMessage_ventilationCount_tag 3
#define IncubationSessionInformationMessage_ventilationDuration_tag 4
#define IncubationSessionInformationMessage_rotationCount_tag 5

/* Struct field encoding specification for nanopb */
extern const pb_field_t IncubationSessionInformationMessage_fields[6];

/* Maximum encoded size of messages (where known) */
#define IncubationSessionInformationMessage_size 28

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define INCUBATIONSESSIONINFORMATIONMESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
