/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu May  2 00:38:34 2019. */

#ifndef PB_REGISTERDEVICEREQUESTMESSAGE_PB_H_INCLUDED
#define PB_REGISTERDEVICEREQUESTMESSAGE_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _RegisterDeviceRequestMessage {
    pb_callback_t serialNumber;
/* @@protoc_insertion_point(struct:RegisterDeviceRequestMessage) */
} RegisterDeviceRequestMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define RegisterDeviceRequestMessage_init_default {{{NULL}, NULL}}
#define RegisterDeviceRequestMessage_init_zero   {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define RegisterDeviceRequestMessage_serialNumber_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t RegisterDeviceRequestMessage_fields[2];

/* Maximum encoded size of messages (where known) */
/* RegisterDeviceRequestMessage_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define REGISTERDEVICEREQUESTMESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
