/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu Apr 25 02:36:10 2019. */

#ifndef PB_SENDCALENDARMESSAGE_PB_H_INCLUDED
#define PB_SENDCALENDARMESSAGE_PB_H_INCLUDED
#include "pb.h"

#include "IncubationSessionInformationMessage.pb.h"

#include "BirdType.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _SendCalendarMessage {
    uint32_t calendarId;
    BirdType birdType;
    pb_callback_t days;
    uint32_t count;
/* @@protoc_insertion_point(struct:SendCalendarMessage) */
} SendCalendarMessage;

typedef struct _SendCalendarMessage_IncubationDayInformationMessage {
    uint32_t dayNumber;
    IncubationSessionInformationMessage information;
/* @@protoc_insertion_point(struct:SendCalendarMessage_IncubationDayInformationMessage) */
} SendCalendarMessage_IncubationDayInformationMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define SendCalendarMessage_init_default         {0, _BirdType_MIN, {{NULL}, NULL}, 0}
#define SendCalendarMessage_IncubationDayInformationMessage_init_default {0, IncubationSessionInformationMessage_init_default}
#define SendCalendarMessage_init_zero            {0, _BirdType_MIN, {{NULL}, NULL}, 0}
#define SendCalendarMessage_IncubationDayInformationMessage_init_zero {0, IncubationSessionInformationMessage_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define SendCalendarMessage_calendarId_tag       1
#define SendCalendarMessage_birdType_tag         2
#define SendCalendarMessage_count_tag            4
#define SendCalendarMessage_days_tag             3
#define SendCalendarMessage_IncubationDayInformationMessage_dayNumber_tag 1
#define SendCalendarMessage_IncubationDayInformationMessage_information_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t SendCalendarMessage_fields[5];
extern const pb_field_t SendCalendarMessage_IncubationDayInformationMessage_fields[3];

/* Maximum encoded size of messages (where known) */
/* SendCalendarMessage_size depends on runtime parameters */
#define SendCalendarMessage_IncubationDayInformationMessage_size 36

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SENDCALENDARMESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
