/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu May  2 00:38:34 2019. */

#ifndef PB_STARTNEWSESSIONWITHBIRDTYPEMESSAGE_PB_H_INCLUDED
#define PB_STARTNEWSESSIONWITHBIRDTYPEMESSAGE_PB_H_INCLUDED
#include "pb.h"

#include "BirdType.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _StartNewSessionWithBirdTypeMessage {
    BirdType birdType;
/* @@protoc_insertion_point(struct:StartNewSessionWithBirdTypeMessage) */
} StartNewSessionWithBirdTypeMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define StartNewSessionWithBirdTypeMessage_init_default {_BirdType_MIN}
#define StartNewSessionWithBirdTypeMessage_init_zero {_BirdType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define StartNewSessionWithBirdTypeMessage_birdType_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t StartNewSessionWithBirdTypeMessage_fields[2];

/* Maximum encoded size of messages (where known) */
#define StartNewSessionWithBirdTypeMessage_size  2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define STARTNEWSESSIONWITHBIRDTYPEMESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
