/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu May  2 00:38:34 2019. */

#ifndef PB_STARTNEWSESSIONWITHCALENDARMESSAGE_PB_H_INCLUDED
#define PB_STARTNEWSESSIONWITHCALENDARMESSAGE_PB_H_INCLUDED
#include "pb.h"

#include "IncubationSessionInformationMessage.pb.h"

#include "BirdType.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _StartNewSessionWithCalendarMessage {
    uint32_t calendarId;
    BirdType birdType;
    pb_callback_t days;
    uint32_t count;
/* @@protoc_insertion_point(struct:StartNewSessionWithCalendarMessage) */
} StartNewSessionWithCalendarMessage;

typedef struct _StartNewSessionWithCalendarMessage_IncubationDayInformationMessage {
    uint32_t dayNumber;
    IncubationSessionInformationMessage information;
/* @@protoc_insertion_point(struct:StartNewSessionWithCalendarMessage_IncubationDayInformationMessage) */
} StartNewSessionWithCalendarMessage_IncubationDayInformationMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define StartNewSessionWithCalendarMessage_init_default {0, _BirdType_MIN, {{NULL}, NULL}, 0}
#define StartNewSessionWithCalendarMessage_IncubationDayInformationMessage_init_default {0, IncubationSessionInformationMessage_init_default}
#define StartNewSessionWithCalendarMessage_init_zero {0, _BirdType_MIN, {{NULL}, NULL}, 0}
#define StartNewSessionWithCalendarMessage_IncubationDayInformationMessage_init_zero {0, IncubationSessionInformationMessage_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define StartNewSessionWithCalendarMessage_calendarId_tag 1
#define StartNewSessionWithCalendarMessage_birdType_tag 2
#define StartNewSessionWithCalendarMessage_count_tag 4
#define StartNewSessionWithCalendarMessage_days_tag 3
#define StartNewSessionWithCalendarMessage_IncubationDayInformationMessage_dayNumber_tag 1
#define StartNewSessionWithCalendarMessage_IncubationDayInformationMessage_information_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t StartNewSessionWithCalendarMessage_fields[5];
extern const pb_field_t StartNewSessionWithCalendarMessage_IncubationDayInformationMessage_fields[3];

/* Maximum encoded size of messages (where known) */
/* StartNewSessionWithCalendarMessage_size depends on runtime parameters */
#define StartNewSessionWithCalendarMessage_IncubationDayInformationMessage_size 36

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define STARTNEWSESSIONWITHCALENDARMESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
