/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu May  2 00:38:34 2019. */

#ifndef PB_STARTNEWSESSIONMESSAGE_PB_H_INCLUDED
#define PB_STARTNEWSESSIONMESSAGE_PB_H_INCLUDED
#include "pb.h"

#include "StartNewSessionWithBirdTypeMessage.pb.h"

#include "StartNewSessionWithCalendarMessage.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _StartNewSessionMessage {
    bool has_startNewSessionWithBirdTypeMessage;
    StartNewSessionWithBirdTypeMessage startNewSessionWithBirdTypeMessage;
    bool has_startNewSessionWithCalendarMessage;
    StartNewSessionWithCalendarMessage startNewSessionWithCalendarMessage;
/* @@protoc_insertion_point(struct:StartNewSessionMessage) */
} StartNewSessionMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define StartNewSessionMessage_init_default      {false, StartNewSessionWithBirdTypeMessage_init_default, false, StartNewSessionWithCalendarMessage_init_default}
#define StartNewSessionMessage_init_zero         {false, StartNewSessionWithBirdTypeMessage_init_zero, false, StartNewSessionWithCalendarMessage_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define StartNewSessionMessage_startNewSessionWithBirdTypeMessage_tag 1
#define StartNewSessionMessage_startNewSessionWithCalendarMessage_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t StartNewSessionMessage_fields[3];

/* Maximum encoded size of messages (where known) */
#define StartNewSessionMessage_size              (19 + StartNewSessionWithCalendarMessage_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define STARTNEWSESSIONMESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
